services:
  - type: web
    name: ai-agents-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
  - type: static
    name: ai-agents-frontend
    rootDir: frontend
    staticPublishPath: .
